### ISSUE TITLE
Entry on SlideMenuView

### ISSUE THREAD

**Issue by MtMovo** [XAM-Consulting/SlideOverKit#8]
Trying to use this awesome component to create a right side menu for a user to put a comment regarding the document displayed on main page. 
The thing is, when a text input (Entry) gets focused, the keyboard slides up and the whole menu disappears. If a click a toolbar item to display the menu again, it shows up with the input focused.

Is there any way to prevent this (disappearing) from happening?

**Comment by marcojak** [comment]
I have the same problem.
Do you know if it's possible to solve this problem?

this is a great component but if I cannot add an Entry, I cannot use it.
Any help?

Thank you

**Comment by MtMovo** [comment]
Nope, haven't found a solution that will work with this component.
Trying a different approach now.
Will let you know if i come up with a solution.

**Comment by MtMovo** [comment]
@marcojak Was able to get a result i wanted without this component. I used two Content pages with grid layout and a button which simply adds another page to a certain grid column. It doesn't provide nice animations, but it suits my needs.

**Comment by jessejiang0214** [comment]
Fixed 4d1c5b09c3ecf1e2250374d72e38c2a9611c2d70

**Comment by oscar21** [comment]
Today I have installed SlideOverKit v2.1.3 and the problem still, jessejiang0214, do you know what is happen?.

**Comment by jessejiang0214** [comment]
What's your environment, I have fixed this on iOS and Android. Does the right menu sample on your side still have this issue?

**Comment by oscar21** [comment]
I´m working on iOS and Android and I am having this problem still. this is my code on the Master:

<?xml version="1.0" encoding="utf-8" ?>
<t:SlideMenuView xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:t="clr-namespace:SlideOverKit"
             x:Class="Nimbeat.Pages.Campaigns.SelfieCampaignDir.RightMenuListSelfieCampaign">
  
  <StackLayout Padding="10, 30, 10, 10"  BackgroundColor="{StaticResource ColorFondoApp}">
    <Label Text="Filtros de Busqueda" FontSize="18" Grid.ColumnSpan="2" XAlign="Center" YAlign="Center" TextColor="Black" />

    <Label Text="Codigo" FontSize="15" Grid.ColumnSpan="2" XAlign="Start" YAlign="Start" TextColor="Black" />
    <Entry x:Name="entFilterCode" Placeholder="*******" HeightRequest="40" VerticalOptions="Start" TextColor="{StaticResource ColorBlueNimbeat}" BackgroundColor="White"/>
    <Button Text="BUSCAR"  Style="{StaticResource BotonNaranja}" Clicked="findSelfieCampaignByFilters"></Button>
  </StackLayout>
  
</t:SlideMenuView>



And my class have this code:

public RightMenuListSelfieCampaign()
        {
            InitializeComponent();
            // You must set IsFullScreen in this case, 
            // otherwise you need to set HeightRequest, 
            // just like the QuickInnerMenu sample
            this.IsFullScreen = true;
            // You must set WidthRequest in this case
            this.WidthRequest = 250;
            this.MenuOrientations = MenuOrientation.RightToLeft;

            // You must set BackgroundColor, 
            // and you cannot put another layout with background color cover the whole View
            // otherwise, it cannot be dragged on Android
            this.BackgroundColor = Color.White;

            // This is shadow view color, you can set a transparent color
            this.BackgroundViewColor = new Color(0, 0, 0, 0.5);
        }

**Comment by steep0001** [comment]
Hi, 
I would like to use this pretty component, but, right now, I have the same issue...
I'm using the 2.1.5 version with Xamarin 2.4.0.38779.
Any solution to solve it?

Thank you

**Comment by oscar21** [comment]
@steep0001 I couldn't get it to work, I had to create my own component.
